name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: python  107SBakst.github.io/Python/project_googlemobility_final.ipynb 
      shell: sh
