name: auto-google-mobility-chart2

on:
  schedule:
    - cron: '55 13 * * 1-5' #Runs at 02:30 everyday
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert altair 
        pip install git+https://github.com/Living-with-machines/gh_orgstats
    - name: Execute report notebook
      env:
        GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
         jupyter nbconvert --to notebook --execute Python/project_googlemobility_final.ipynb
         jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt project_googlemobility_final.nbconvert.ipynb --output project_googlemobility_final.html
         mv *.html docs/
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: SB
        message: "Update GitHub traffic report"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
